packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  typescript: ^5.8.3
  zod: ^3.25.7
  eslint: ^9.27.0
  prettier: ^3.5.3
  tsx: ^4.20.3
  dotenv-cli: ^8.0.0
  vitest: ^3.2.2
  '@vitest/coverage-v8': ^3.2.2
catalogs:
  nextjs:
    next: ^15.3.4
    react: ^19.1.0
    react-dom: ^19.1.0
    tailwindcss: ^4.1.11
    '@tailwindcss/postcss': ^4.1.11
    postcss: ^8.5.6
    react-dropzone: ^14.3.8
    date-fns: ^4.1.0
    next-themes: ^0.4.6
    '@types/react': ^19.1.3
    '@types/react-dom': ^19.1.2
    '@types/node': ^22.10.5
  api:
    '@trpc/client': ^11.4.3
    '@trpc/server': ^11.4.3
    '@trpc/next': ^11.4.3
    '@trpc/react-query': ^11.4.3
    '@tanstack/react-query': ^5.81.5
    superjson: ^2.2.2
  backend:
    prisma: ^6.9.0
    '@prisma/client': ^6.9.0
    bcryptjs: ^3.0.2
    '@types/bcryptjs': ^2.4.2
    next-auth: ^4.24.7
    '@auth/prisma-adapter': ^2.10.0
  storage:
    glob: ^11.0.3
    file-type: ^19.6.0
  devtools:
    '@vitest/ui': ^3.2.2
    '@types/node': ^22.10.5
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
onlyBuiltDependencies:
  - esbuild
  - sharp
