services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: champlain
      POSTGRES_PASSWORD: champlain_dev
      POSTGRES_DB: champlain_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U champlain -d alchemy_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  postgres_data:
  valkey_data:
